# Generated by Django 5.2.16 on 2026-07-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=160)),
                ('receipt_id', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('PENDING', 'Pending (발행 대기)'), ('PUBLISHED', 'Published (발행 완료)'), ('FAILED', 'Failed (발행 실패)')], default='PENDING', max_length=16)),
                ('idempotency_key', models.CharField(blank=True, max_length=220, null=True, unique=True)),
                ('target_topic', models.CharField(blank=True, help_text='실제 퍼블리시된 ROS2 토픽 이름 또는 시뮬레이터 엔드포인트 경로 (예: /cmd_vel)', max_length=255)),
                ('adapter', models.CharField(default='sim', help_text='발행에 사용된 어댑터 (예: sim, ros2)', max_length=32)),
                ('message_type', models.CharField(blank=True, help_text='발행된 ROS2 메시지 타입 (예: geometry_msgs/Twist)', max_length=120)),
                ('robot_id', models.CharField(default='default-robot', max_length=120)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('workspace_context', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Execution record',
                'verbose_name_plural': 'Execution records',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
