# Generated by Django 5.2.16 on 2026-07-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_id', models.CharField(max_length=160, unique=True)),
                ('ticket_id', models.CharField(max_length=160)),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=16)),
                ('evaluated_policy_ids', models.JSONField(blank=True, default=list)),
                ('passed_policy_ids', models.JSONField(blank=True, default=list)),
                ('failed_policy_ids', models.JSONField(blank=True, default=list)),
                ('evaluated_policies', models.JSONField(blank=True, default=list)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('approved_by', models.CharField(default='safety-gatekeeper', max_length=128)),
                ('valid', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('exact_ticket_hash', models.CharField(blank=True, max_length=64)),
                ('approved_max_velocity', models.FloatField(blank=True, null=True)),
                ('approved_max_steering_angle', models.FloatField(blank=True, null=True)),
                ('workspace_context', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Approval receipt',
                'verbose_name_plural': 'Approval receipts',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SafetyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.CharField(max_length=160, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('scope', models.CharField(choices=[('global', 'Global (all robots)'), ('robot', 'Specific robot'), ('platform', 'Platform class (e.g. ackermann, diff-drive)')], default='global', max_length=16)),
                ('scope_target', models.CharField(blank=True, help_text='scope=robot/platform일 때의 대상 식별자', max_length=120)),
                ('max_velocity', models.FloatField(blank=True, help_text='허용 가능한 최대 선속도 (m/s)', null=True)),
                ('max_acceleration', models.FloatField(blank=True, help_text='허용 가능한 최대 가속도 (m/s^2)', null=True)),
                ('max_angular_velocity', models.FloatField(blank=True, help_text='허용 가능한 최대 각속도 (rad/s), 차동 구동 계열', null=True)),
                ('max_steering_angle', models.FloatField(blank=True, help_text='허용 가능한 최대 조향각 (rad), Ackermann 계열', null=True)),
                ('max_steering_rate', models.FloatField(blank=True, help_text='허용 가능한 최대 조향각 변화율 (rad/s)', null=True)),
                ('min_time_to_collision', models.FloatField(blank=True, help_text='최소 TTC(Time-To-Collision, 초). 이보다 낮으면 정책 위반.', null=True)),
                ('min_obstacle_distance', models.FloatField(blank=True, help_text='장애물까지 허용되는 최소 거리 (m)', null=True)),
                ('applicable_command_types', models.JSONField(blank=True, default=list, help_text='["velocity", "ackermann", "trajectory", ...] 형태, 비어있으면 전체 적용')),
                ('active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100, help_text='낮을수록 먼저 평가됨 (정렬용)')),
                ('workspace_context', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Safety policy',
                'verbose_name_plural': 'Safety policies',
                'ordering': ['priority', 'policy_id'],
            },
        ),
    ]
