# Generated by Django 5.2.16 on 2026-07-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=160, unique=True)),
                ('source', models.CharField(default='motion-planner', max_length=32)),
                ('robot_id', models.CharField(default='default-robot', max_length=120)),
                ('mission_id', models.CharField(blank=True, max_length=120)),
                ('frame_id', models.CharField(default='base_link', max_length=64)),
                ('command_type', models.CharField(choices=[('velocity', 'Velocity (Twist: linear + angular)'), ('ackermann', 'Ackermann drive (velocity + steering angle)'), ('trajectory', 'Trajectory (waypoint sequence)'), ('stop', 'Controlled stop'), ('emergency_stop', 'Emergency stop (E-STOP)')], default='velocity', max_length=32)),
                ('target_velocity', models.FloatField(blank=True, help_text='목표 선속도 (m/s)', null=True)),
                ('target_angular_velocity', models.FloatField(blank=True, help_text='목표 각속도 (rad/s), 차동 구동 계열 명령', null=True)),
                ('steering_angle', models.FloatField(blank=True, help_text='목표 조향각 (rad), Ackermann 계열 명령', null=True)),
                ('target_acceleration', models.FloatField(blank=True, help_text='목표 가속도 (m/s^2)', null=True)),
                ('max_velocity_limit', models.FloatField(blank=True, help_text='이 명령에 적용되는 최대 속도 한계 (m/s)', null=True)),
                ('max_duration_ms', models.PositiveIntegerField(blank=True, help_text='명령 유효 지속 시간 (ms), 초과 시 재계획 필요', null=True)),
                ('waypoints', models.JSONField(blank=True, default=list, help_text='[{x, y, theta, velocity}, ...] 형태의 경로점 목록')),
                ('target_pose', models.JSONField(blank=True, default=dict, help_text='{x, y, theta} 형태의 목표 자세 (선택)')),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('emergency', 'Emergency')], default='normal', max_length=16)),
                ('status', models.CharField(default='DRAFT', max_length=32)),
                ('current_state', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_SAFETY_REVIEW', 'Pending safety review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXECUTING', 'Executing'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=32)),
                ('approval_receipt_id', models.CharField(blank=True, max_length=160)),
                ('payload_hash', models.CharField(blank=True, max_length=64)),
                ('user_visible_summary', models.TextField(blank=True)),
                ('created_by', models.CharField(default='motion-planner', max_length=128)),
                ('natural_language_source', models.TextField(blank=True)),
                ('workspace_context', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Command ticket',
                'verbose_name_plural': 'Command tickets',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
